# Generated by Django 2.1.4 on 2019-01-03 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('chatsession', models.AutoField(primary_key=True, serialize=False)),
                ('esttime', models.FloatField(null=True, verbose_name='Seconds')),
            ],
        ),
        migrations.CreateModel(
            name='Claims',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('goal', models.CharField(max_length=255)),
                ('hobbies', models.CharField(max_length=255)),
                ('lat', models.FloatField(null=True, verbose_name='Latitude')),
                ('lon', models.FloatField(null=True, verbose_name='Longitude')),
                ('esttime', models.FloatField(null=True, verbose_name='Seconds')),
                ('wholikes', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('sender', models.CharField(max_length=255)),
                ('receiver', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chatsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='music.ChatSession')),
            ],
        ),
    ]
