# Generated by Django 2.1.4 on 2019-01-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='name',
            field=models.CharField(default='Oleg', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatsession',
            name='user1',
            field=models.CharField(default='Oleg', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatsession',
            name='user2',
            field=models.CharField(default='Mari', max_length=255),
            preserve_default=False,
        ),
    ]
