# Generated by Django 2.1.4 on 2019-01-03 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20190103_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='chatsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.ChatSession'),
        ),
    ]
