# Generated by Django 2.1.4 on 2019-01-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20190103_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='esttime',
            field=models.FloatField(blank=True, null=True, verbose_name='Seconds'),
        ),
        migrations.AlterField(
            model_name='claims',
            name='goal',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='claims',
            name='hobbies',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='claims',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='claims',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='claims',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='claims',
            name='wholikes',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
