# Generated by Django 2.1.4 on 2019-01-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20190103_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='wholikes',
            field=models.CharField(blank=True, default='Mari', max_length=255),
            preserve_default=False,
        ),
    ]
