# Generated by Django 2.1.4 on 2019-01-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20190103_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='name',
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='esttime',
            field=models.FloatField(blank=True, null=True, verbose_name='Seconds'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='users',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
