# Generated by Django 2.1.4 on 2019-01-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20190104_0141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claims',
            old_name='hobbies',
            new_name='lookfor',
        ),
        migrations.AddField(
            model_name='claims',
            name='iam',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
